'use strict';
const checkButton=el('button','button primary','Проверить новости');
$('.topbar').append(checkButton);
const checkDialog=el('dialog','check-modal');
checkDialog.setAttribute('aria-label','Запуск проверки новостей');
checkDialog.append(el('h2','','Проверить новости сейчас'),el('p','','Проверка работает в облаке. Пока серверный обработчик не развёрнут, запуск подтверждается в GitHub: войдите в свой аккаунт и нажмите Run workflow. Компьютер можно выключить после запуска.'));
checkDialog.append(link('Открыть запуск в GitHub ↗','https://github.com/dsxx1/cbr-regulatory-monitor/actions/workflows/check-news.yml','button primary'));
const closeCheck=el('button','button','Закрыть');closeCheck.onclick=()=>checkDialog.close();checkDialog.append(closeCheck);document.body.append(checkDialog);checkButton.onclick=()=>checkDialog.showModal();
const criteria=el('details','criteria');criteria.append(el('summary','','Как определяется важность'));
const criteriaList=el('ul');
for(const text of ['Важно — существенное изменение обязанностей, сроков, платежей, отчётности или риска остановки работы. В карточке должны быть основания и условия применимости.','Подготовиться — возможное изменение процесса или проект, требующий внимания; это ещё не действующая обязанность.','Учесть — небольшое организационное изменение.','Для сведения — статистика, мероприятия и материалы без изменения требований.','Не оценено — разбор не готов. Это не означает, что новость неважная.'])criteriaList.append(el('li','',text));
criteria.append(criteriaList);$('#feedView').prepend(criteria);
for(const p of ['high','medium','low','news']){const b=$(`#priorityFilters [data-priority="${p}"]`);b.replaceChildren(el('span','dot '+p),document.createTextNode(priorities[p]));}
$('.footnote').textContent='Важность определяется по последствиям и основаниям в полном тексте. Применимость к компании и срок исполнения проверяются отдельно. Неготовый разбор не считается проверенной новостью.';
const previousQuality=qualityView;
qualityView=function(){previousQuality();const h=data.llmHealth||{};const p=panel('Бесплатные LLM: фактические попытки',h.attempts?`${h.attempts} попыток: ${h.responses} ответов, ${h.failures} отказов. Ответ API ещё не означает качественный разбор.`:'Новый журнал ещё не накопил попыток. Данных для оценки стабильности пока нет.');p.classList.add('transport-log');p.append(el('p','',h.window||'Журнал начинается с включения измерений; прежние ошибки не восстановлены.'));for(const e of (h.events||[]).slice(-12).reverse()){const row=el('div','source-row');row.append(el('strong','',e.route),el('span','',`${e.status==='response'?'Ответ получен':'Неудачная попытка'} · ${(e.ms/1000).toFixed(1)} с · ${formatDate(e.at,true)}`));if(e.reason)row.append(el('small','',({rate_limit:'Лимит провайдера',timeout:'Истекло время ожидания',truncated:'Ответ обрезан',cost:'Цена не нулевая',provider_error:'Ошибка провайдера'})[e.reason]||'Ошибка'));p.append(row);}$('#qualityView').prepend(p);};

let serviceState=null,lastJobState='';
const serviceStrip=el('div','status-strip');serviceStrip.setAttribute('role','status');$('#stats').before(serviceStrip);
async function apiPost(path,body={}){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Monitor-Token':serviceState.token},body:JSON.stringify(body)});const value=await r.json();if(!r.ok)throw Error(value.error||'Запрос не выполнен');return value;}
const scheduleButton=el('button','button','Расписание выключено');
scheduleButton.onclick=async()=>{try{await apiPost('/api/schedule',{enabled:serviceState.schedule!=='on'});await serviceRefresh();}catch(e){toast(e.message);}};
const taskButton=el('button','button','Создать задачу в Б24');taskButton.hidden=true;$('.reader-actions').append(taskButton);
taskButton.onclick=async()=>{if(!current?.brief)return toast('Сначала нужен проверенный разбор');if(!confirm('Создать заполненную задачу на владельца вебхука Б24? Срок исполнения не назначается автоматически.'))return;taskButton.disabled=true;try{const result=await apiPost('/api/task',{id:current.id});toast('Задача Б24 №'+result.taskId+' создана. Ссылка поставлена в очередь отправки боту.');}catch(e){toast(e.message);}finally{taskButton.disabled=false;}};
async function serviceRefresh(){try{const r=await fetch('/api/status',{cache:'no-store'});if(!r.ok)throw Error('offline');serviceState=await r.json();if(!serviceState.token)throw Error('offline');if(!scheduleButton.isConnected)$('.topbar').append(scheduleButton);taskButton.hidden=false;checkButton.textContent='Проверить новости';checkButton.onclick=async()=>{try{await apiPost('/api/check');await serviceRefresh();}catch(e){toast(e.message);}};scheduleButton.textContent=serviceState.schedule==='on'?'Расписание: каждый час · выключить':'Расписание выключено · включить';const j=serviceState.job;serviceStrip.textContent=(j?`${j.stage||j.state}${j.error?' · '+j.error:''}`:'Проверка ещё не запускалась')+` · Сообщений в очереди: ${serviceState.pendingMessages}`+(serviceState.b24Configured?'':' · Б24 не настроен: заполните secrets.txt и перезапустите контейнер');$('.cloud-dot').textContent='Локальный контейнер';$('.sidebar-bottom p').textContent='Работает, пока включены ПК и контейнер. GitHub Actions отключены.';if(j?.state==='done'&&lastJobState!==`${j.id}:done`)await load();lastJobState=j?`${j.id}:${j.state}`:'';}catch{serviceStrip.textContent='Это опубликованная копия сайта. GitHub Actions отключены. Для запуска откройте локальный сайт http://localhost:8787.';checkButton.textContent='Где запустить проверку';checkButton.onclick=()=>alert('GitHub Actions отключены. Откройте http://localhost:8787 на компьютере с контейнером.');}}
const processStop=el('button','button','Остановить процесс');
const localJournal=$('.sidebar-bottom a');localJournal.textContent='Журнал процесса';localJournal.href='#quality';localJournal.removeAttribute('target');localJournal.onclick=e=>{e.preventDefault();switchView('quality');};
const beforeLocalQuality=qualityView;
qualityView=function(){beforeLocalQuality();if(serviceState?.history){const p=panel('Журнал локального процесса','Последние проверки. GitHub Actions не используются.');for(const j of serviceState.history){const row=el('div','source-row');row.append(el('strong','',`Проверка №${j.id} · ${j.stage}`),el('small','',formatDate(j.started,true)+(j.finished?' — '+formatDate(j.finished,true):'')+(j.error?' · '+j.error:'')));p.append(row);}$('#qualityView').append(p);}};
const oldSettingsView=settingsView;
settingsView=function(){if(!serviceState)return oldSettingsView();if(serviceState.settings)data.settings=serviceState.settings;const root=$('#settingsView');root.replaceChildren();const p=panel('Бесплатные модели','Настройки сохраняются в локальном процессе и применяются к следующему запуску. Платного переключения нет.');for(const [key,label] of [['generator','Генератор'],['reviewer','Проверяющий']]){const row=el('label','setting',label);const select=el('select');select.id='setting-'+key;for(const model of data.models){const option=el('option','',model);option.value=model;select.append(option);}select.value=data.settings[key];row.append(select);p.append(row);}const limit=el('select');limit.id='setting-max';limit.setAttribute('aria-label','Лимит документов');for(let i=1;i<=5;i++){const o=el('option','',String(i));o.value=i;limit.append(o);}limit.value=data.settings.max_calls;p.append(el('p','','Документов из текущей очереди за проверку. Дополнительно обрабатываются до трёх архивных материалов.'),limit);const save=el('button','button primary','Сохранить настройки');save.onclick=async()=>{try{data.settings=await apiPost('/api/settings',draftSettings());serviceState.settings=data.settings;toast('Сохранено. Применится к следующей проверке.');}catch(e){toast(e.message);}};p.append(save);root.append(p,panel('Управление','Кнопки проверки, расписания и остановки процесса находятся сверху. Расписание проверяет раз в час, пока процесс запущен.'));};
const oldSourcesView=sourcesView;
sourcesView=function(){oldSourcesView();if(serviceState){const first=$('#sourcesView').firstElementChild;first.replaceChildren(el('h2','','Расписание локального процесса'),el('p','',serviceState.schedule==='on'?'Проверка каждый час, пока процесс запущен.':'Расписание выключено. Проверку можно запустить кнопкой.'),el('p','','Последняя проверка источников: '+formatDate(data.status.checked,true)+' ЕКБ'));}};
processStop.onclick=async()=>{if(!confirm('Остановить мониторинг и текущую проверку? Для запуска откройте ЗАПУСТИТЬ.cmd.'))return;try{await apiPost('/api/stop');serviceStrip.textContent='Процесс остановлен. Данные сохранены.';}catch(e){toast(e.message);}};
const baseServiceRefresh=serviceRefresh;
serviceRefresh=async function(){await baseServiceRefresh();if(serviceStrip.textContent.startsWith('Это опубликованная копия')){serviceState=null;serviceStrip.textContent='Процесс остановлен или недоступен. Для запуска откройте ЗАПУСТИТЬ.cmd.';$('.cloud-dot').textContent='Процесс недоступен';return;}if(serviceState?.runtime==='local'){if(!processStop.isConnected)$('.topbar').append(processStop);$('.cloud-dot').textContent='Локальный процесс · PID '+serviceState.pid;$('.sidebar-bottom p').textContent='Видимое окно «Мониторинг регулятора». GitHub Actions отключены.';if(serviceState.health&&data){data.llmHealth=serviceState.health;if(view==='quality')qualityView();}const progress=$('#backlogProgress');if(progress){const text=progress.querySelector('span');if(text)text.textContent='Разбор запускается кнопкой или по включённому расписанию. '+(data?.backlog?.last_finished?'Последняя порция: '+formatDate(data.backlog.last_finished,true):'');}}};
if(['localhost','127.0.0.1'].includes(location.hostname)){serviceRefresh();setInterval(()=>serviceRefresh(),5000);}else{serviceStrip.textContent='GitHub Actions отключены. Управление перенесено в локальный процесс: http://localhost:8787.';checkButton.textContent='Локальный запуск';checkButton.onclick=()=>alert('Откройте http://localhost:8787 на компьютере с запущенным мониторингом.');}
